version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - net_dev
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=graphql
      - DB_USERNAME=dev
      - DB_PASSWORD=password
    depends_on:
      - mysql

  web:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - net_dev
    depends_on:
      - app

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: graphql
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - net_dev

networks:
  net_dev:
    driver: bridge

volumes:
  mysql_data:
    driver: local
